### ISSUE TITLE
Which programming language is this written in?

### ISSUE THREAD

**Issue by anonimo82** [MahmoudFayed/PWCT_Mirror_From_Sourceforge#1]
Hello everyone.
As in subject, which programming language is this written in?

Thanks in advance for any help.

Regards, have a nice day.

**Comment by MahmoudFayed** [comment]
This is PWCT1 (First Generation)
The Visual Environment is developed using Visual FoxPro 9.0 SP2: https://en.wikipedia.org/wiki/Visual_FoxPro
The Visual Components are developed using a custom domain specific language called RPWI: https://[doublesvsoop.sourceforge.net/pwcthelp/features/frameworkandextension.htm](https://doublesvsoop.sourceforge.net/pwcthelp/features/frameworkandextension.htm) 
The Visual Components includes source code written in the target programming language (Harbour, C, Python, Supernova, C#, etc.)

With respect to PWCT2 (Not Open Source) - Everything is developed using the Ring programming language: https://github.com/ring-lang/ring/tree/master/marketing/pwct
